// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/23/2025, 12:11:42 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Talentify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/plugins/**/*.{js,ts,mjs}","E:/Talentify/composables/**/*.{js,ts,mjs}","E:/Talentify/utils/**/*.{js,ts,mjs}","E:/Talentify/pages/index.vue","E:/Talentify/pages/sign-in.vue","E:/Talentify/pages/sign-up.vue","E:/Talentify/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Talentify/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;