// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/29/2025, 1:16:45 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Vortexify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/plugins/**/*.{js,ts,mjs}","E:/Vortexify/composables/**/*.{js,ts,mjs}","E:/Vortexify/utils/**/*.{js,ts,mjs}","E:/Vortexify/pages/about.vue","E:/Vortexify/pages/index.vue","E:/Vortexify/pages/pricing.vue","E:/Vortexify/pages/sign-in.vue","E:/Vortexify/pages/sign-up.vue","E:/Vortexify/pages/sign-up/recruiter.vue","E:/Vortexify/pages/sign-up/job-seeker.vue","E:/Vortexify/pages/post-job.vue","E:/Vortexify/pages/job-alerts.vue","E:/Vortexify/pages/browse-jobs.vue","E:/Vortexify/pages/features/index.vue","E:/Vortexify/pages/resume-builder.vue","E:/Vortexify/pages/career-resources.vue","E:/Vortexify/pages/browse-candidates.vue","E:/Vortexify/pages/salary-calculator.vue","E:/Vortexify/pages/features/advanced-analytics.vue","E:/Vortexify/pages/features/smart-job-matching.vue","E:/Vortexify/pages/features/secure-hiring-process.vue","E:/Vortexify/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Vortexify/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;